import type { TroubleshootingCaseDefinition } from '@main/services/troubleshooting/types'
import { meta, ttCase } from './_shared'

export const asyncVerifyCases: TroubleshootingCaseDefinition[] = [
  ttCase({
    id: 'tiktok-repost-v1.async-verify.nonblocking-smoke',
    title: 'Async Verify Non-blocking Smoke',
    description: 'Publisher schedules background verify task and returns immediately; loop proceeds to next item.',
    risk: 'safe',
    category: 'async_verify',
    group: 'async_verify',
    tags: ['async-task', 'publish-verify', 'nonblocking', 'db', 'events'],
    level: 'advanced',
    implemented: false,
    meta: meta({
      parameters: [{ key: 'fixturePublishOutcome', value: 'under_review' }],
      checks: {
        db: ['async_tasks row created with pending status and dedupe_key', 'campaign video status=under_review while loop continues'],
        logs: ['Scheduler enqueue and non-blocking handoff logged'],
        events: ['Publish status event includes next retry metadata for UI'],
      },
      passMessages: ['Loop throughput unaffected by long publish verification waits'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.async-verify.lease-reclaim',
    title: 'Async Verify Lease Reclaim',
    description: 'Expired running async verify task is reclaimed on scheduler restart and resumes safely.',
    risk: 'safe',
    category: 'async_verify',
    group: 'async_verify',
    tags: ['async-task', 'lease', 'recovery', 'edge', 'db'],
    level: 'advanced',
    implemented: false,
    meta: meta({
      parameters: [
        { key: 'fixtureTaskState', value: 'running with expired leaseUntil' },
        { key: 'schedulerRestart', value: true },
      ],
      checks: {
        db: ['Expired leased task transitions back to pending (or is reclaimed atomically)', 'Attempt/lease metadata remains consistent after reclaim'],
        logs: ['Reclaim action and worker/task ids logged'],
      },
      errorMessages: ['No double-execute after lease reclaim'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.async-verify.dedupe-active-task',
    title: 'Async Verify Dedupe Active Task',
    description: 'Repeated scheduling for same video/account dedupes to one active async verify task.',
    risk: 'safe',
    category: 'async_verify',
    group: 'async_verify',
    tags: ['async-task', 'dedupe', 'db', 'edge'],
    level: 'advanced',
    implemented: false,
    meta: meta({
      parameters: [{ key: 'dedupeKeyPattern', value: 'publish-verify:{videoId}:{accountId}' }],
      checks: {
        db: ['Only one active async verify task exists per dedupe key', 'Subsequent schedule attempts return existing/duplicate outcome without new row'],
        logs: ['Dedupe hit is logged with existing task id'],
      },
      passMessages: ['Duplicate task scheduling does not create conflicting background workers'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.async-verify.timeout-manual-check',
    title: 'Async Verify Timed Out → Manual Check',
    description: 'Async verify reaches max attempts and transitions to timed_out/manual-check path with UI-visible next steps.',
    risk: 'safe',
    category: 'async_verify',
    group: 'async_verify',
    tags: ['async-task', 'timeout', 'manual-check', 'db', 'events'],
    level: 'advanced',
    implemented: false,
    meta: meta({
      parameters: [
        { key: 'fixtureRecheckResult', value: 'always-under_review' },
        { key: 'maxAttempts', value: 3 },
      ],
      checks: {
        db: ['async_tasks status=timed_out with attempts=maxAttempts', 'campaign video remains under_review (or manual_check) with retry metadata'],
        ui: ['Debug/campaign UI shows manual-check guidance and final retry info'],
        logs: ['Attempts and timeout decision logged with final reason'],
        events: ['Notification/event emitted for manual follow-up'],
      },
      passMessages: ['Timed-out async verification is explicit, recoverable, and non-blocking'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.async-verify.concurrency-key-serialization',
    title: 'Async Verify Concurrency Key Serialization',
    description: 'Multiple async verify tasks for same account respect concurrencyKey/maxConcurrent and execute sequentially.',
    risk: 'safe',
    category: 'async_verify',
    group: 'async_verify',
    tags: ['async-task', 'concurrency', 'account', 'edge', 'db'],
    level: 'advanced',
    implemented: false,
    meta: meta({
      parameters: [
        { key: 'fixtureTasksSameAccount', value: 3 },
        { key: 'maxConcurrent', value: 1 },
      ],
      checks: {
        db: ['At most one running task per concurrency_key at any moment', 'Other tasks remain pending and later complete/reschedule'],
        logs: ['Claim/release/skip due to concurrency limit logged with task ids'],
      },
      errorMessages: ['No thrash loop or duplicate execute for same account queue'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.async-verify.max-retries-exceeded-manual-fallback',
    title: 'Async Verify Max Retries Exceeded → Manual Fallback',
    description: 'Verify task exceeds maxAttempts; task transitions to manual_check and UI surfaces actionable next steps.',
    risk: 'safe',
    category: 'async_verify',
    group: 'async_verify',
    tags: ['async-task', 'max-retries', 'manual-check', 'db'],
    level: 'advanced',
    implemented: false,
    meta: meta({
      parameters: [{ key: 'maxAttempts', value: 5 },{ key: 'fixtureOutcome', value: 'always-under_review' }],
      checks: {
        db: ['async_tasks.status=manual_check with attempts=maxAttempts', 'campaign video remains under_review with retry metadata'],
        logs: ['Max retry exhaustion logged with reason and total wait time'],
        events: ['Manual-check notification emitted with video context'],
      },
      passMessages: ['Max retries exhaustion path is deterministic and non-blocking'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.async-verify.worker-crash-mid-verify',
    title: 'Async Verify Worker Crash Mid-Verification',
    description: 'Worker crashes while verifying; verify lease expiry and task reclaim resets state correctly for next worker.',
    risk: 'safe',
    category: 'async_verify',
    group: 'async_verify',
    tags: ['async-task', 'crash', 'lease', 'reclaim', 'edge'],
    level: 'advanced',
    implemented: false,
    meta: meta({
      parameters: [{ key: 'fixtureCrashAfterMs', value: 500 },{ key: 'leaseDurationMs', value: 5000 }],
      checks: {
        db: ['Task lease expires and status resets to pending after leaseUntil passes', 'No corrupt attempt counter from crash'],
        logs: ['Lease expiry detected on reclaim; attempt count incremented'],
      },
      passMessages: ['Crashed worker lease is safely reclaimed by next scheduler tick'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.async-verify.result-persisted-correct-campaign',
    title: 'Async Verify Result Persisted to Correct Campaign',
    description: 'Background verify completion updates the correct campaign video, not another campaign with similar platform_id.',
    risk: 'safe',
    category: 'async_verify',
    group: 'async_verify',
    tags: ['async-task', 'isolation', 'campaign', 'db', 'edge'],
    level: 'advanced',
    implemented: false,
    meta: meta({
      parameters: [{ key: 'fixtureCampaignCount', value: 2 },{ key: 'sharedPlatformId', value: 'same platform_id in 2 campaigns' }],
      checks: {
        db: ['Only the video in the target campaign is updated', 'Other campaign video with same platform_id is untouched'],
        logs: ['Verify result scoped by campaign_id + platform_id, not platform_id alone'],
      },
      passMessages: ['Async verify result is campaign-scoped; no cross-campaign contamination'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.async-verify.queue-backpressure',
    title: 'Async Verify Queue Backpressure (Many Pending Tasks)',
    description: '50+ pending verify tasks queue up; verify scheduler processes them sequentially per concurrency key without memory spike or starvation.',
    risk: 'safe',
    category: 'async_verify',
    group: 'async_verify',
    tags: ['async-task', 'queue', 'backpressure', 'performance', 'edge'],
    level: 'advanced',
    implemented: false,
    meta: meta({
      parameters: [{ key: 'fixturePendingTaskCount', value: 50 },{ key: 'maxConcurrent', value: 2 }],
      checks: {
        db: ['All 50 tasks eventually complete or timeout without DB deadlock', 'Max concurrent running === maxConcurrent at each tick'],
        logs: ['Queue depth and drain rate logged at each scheduler tick'],
      },
      passMessages: ['High-volume verify queue drains in bounded time without system degradation'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.async-verify.cross-worker-dedup-safety',
    title: 'Async Verify Cross-Worker Dedup Safety',
    description: 'Two scheduler ticks fire nearly simultaneously; only one worker successfully claims each task due to atomic lease.',
    risk: 'safe',
    category: 'async_verify',
    group: 'async_verify',
    tags: ['async-task', 'dedup', 'concurrency', 'race', 'edge'],
    level: 'advanced',
    implemented: false,
    meta: meta({
      parameters: [{ key: 'fixtureTickIntervalMs', value: 50 },{ key: 'secondTickDelayMs', value: 10 }],
      checks: {
        db: ['Each task has exactly one running worker at a time (atomic claim)', 'No double-execute evidence in attempt history'],
        logs: ['Claim collision: one worker succeeds, other skips with \'already claimed\' log'],
      },
      passMessages: ['Atomic lease prevents double-execution under concurrent scheduler ticks'],
    }),
  }),
]
