import type { TroubleshootingCaseDefinition } from '@main/services/troubleshooting/types'
import { meta, ttCase } from './_shared'

export const publishCases: TroubleshootingCaseDefinition[] = [
  ttCase({
    id: 'tiktok-repost-v1.publish.public-path',
    title: 'Publish Path (Public Immediate)',
    description: 'Publish returns public immediately; publish_history, counters, and UI status all update correctly.',
    risk: 'real_publish',
    category: 'publish',
    group: 'publish',
    tags: ['publish', 'public', 'db', 'events', 'artifact:screenshot', 'artifact:html'],
    level: 'advanced',
    implemented: false,
    meta: meta({
      parameters: [
        { key: 'expectedOutcome', value: 'public-immediate' },
        { key: 'requiresCookies', value: true },
        { key: 'requiresLocalVideo', value: true },
      ],
      checks: {
        db: ['publish_history status=published with videoUrl/videoId', 'campaign video status=published and publish_url set', 'published counter increments exactly once'],
        ui: ['Campaign detail status chip updates to PUBLISHED'],
        logs: ['Publish progress + final success logs emitted'],
        events: ['video:publish-status and video:published emitted'],
        files: ['Capture debug artifacts (screenshot/html/session log) if publisher returns them'],
      },
      passMessages: ['Immediate public path verified end-to-end without retry branch'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.publish.under-review-path',
    title: 'Publish Path (Under Review)',
    description: 'Publish returns under_review; verify status transitions, retry/progress logs, and final outcome.',
    risk: 'real_publish',
    category: 'publish',
    group: 'publish',
    tags: ['publish', 'under_review', 'retry', 'artifact:screenshot', 'artifact:html'],
    level: 'advanced',
    implemented: false,
    meta: meta({
      parameters: [{ key: 'expectedOutcome', value: 'under_review or delayed-public' }],
      checks: {
        db: ['publish_history starts as under_review and transitions if later public', 'campaign video status reflects under_review/verifying/published'],
        logs: ['Retry delay, attempt counters, and recheck statuses logged'],
        events: ['Retry-related video:publish-status events emitted'],
        files: ['Dump HTML/screenshot when recheck selector drift suspected'],
      },
      errorMessages: ['Verification failure reason and attempt number captured in logs'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.publish.verification-incomplete-path',
    title: 'Publish Path (verification_incomplete)',
    description: 'Force verification_incomplete branch and ensure it does not regress into under_review behavior.',
    risk: 'real_publish',
    category: 'publish',
    group: 'publish',
    tags: ['publish', 'verification_incomplete', 'regression'],
    level: 'advanced',
    implemented: false,
    meta: meta({
      parameters: [{ key: 'expectedOutcome', value: 'verification_incomplete' }],
      checks: {
        db: ['campaign video status=verification_incomplete', 'publish_history stored as published when upload succeeded'],
        logs: ['Branch decision explicitly identifies verification_incomplete'],
        events: ['video:published carries verificationIncomplete=true'],
      },
      passMessages: ['verification_incomplete path remains distinct from under_review retry branch'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.publish.duplicate-dedup',
    title: 'Publish Dedup Duplicate Detection',
    description: 'Duplicate source/fingerprint should skip upload and emit duplicate status/event with existing URL.',
    risk: 'safe',
    category: 'publish',
    group: 'publish',
    tags: ['publish', 'dedup', 'duplicate', 'db'],
    level: 'intermediate',
    implemented: false,
    meta: meta({
      parameters: [{ key: 'fixtureDedupMatch', value: 'source_platform_id or file_fingerprint' }],
      checks: {
        db: ['No new upload is attempted when duplicate found', 'campaign video status=duplicate and publish_url points to existing row'],
        logs: ['Duplicate reason + matchedBy logged'],
        events: ['video:duplicate-detected and video:publish-status duplicate emitted'],
      },
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.publish.captcha-event',
    title: 'Publish CAPTCHA Event Handling',
    description: 'CAPTCHA during publish should mark video captcha, emit event, and continue loop safely.',
    risk: 'safe',
    category: 'publish',
    group: 'publish',
    tags: ['publish', 'captcha', 'edge', 'artifact:screenshot', 'artifact:html'],
    level: 'advanced',
    implemented: false,
    meta: meta({
      parameters: [{ key: 'fixtureErrorType', value: 'captcha' }],
      checks: {
        db: ['campaign video status=captcha', 'No failed counter increment unless policy requires it'],
        logs: ['CAPTCHA path logs mention skip/continue behavior'],
        events: ['captcha:detected event emitted with debugArtifacts'],
        files: ['Capture HTML/screenshot around captcha challenge when possible'],
      },
      errorMessages: ['Captcha path should not surface as generic publish failure'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.publish.violation-event',
    title: 'Publish Violation Event Handling',
    description: 'Violation path should set video violation, emit notifications, and preserve debug artifacts.',
    risk: 'safe',
    category: 'publish',
    group: 'publish',
    tags: ['publish', 'violation', 'edge', 'artifact:screenshot', 'artifact:html'],
    level: 'advanced',
    implemented: false,
    meta: meta({
      parameters: [{ key: 'fixtureErrorType', value: 'violation' }],
      checks: {
        db: ['campaign video status=violation', 'No publish counter increment'],
        logs: ['Violation message includes video id + context'],
        events: ['violation:detected event emitted with description/author/debugArtifacts'],
        files: ['Debug artifacts retained for manual review'],
      },
      passMessages: ['Violation path is explicit and recoverable for subsequent items'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.publish.cookies-expired-preflight',
    title: 'Publish Session Expired / Cookie Invalid',
    description: 'Publish preflight detects invalid/expired cookies, fails clearly, and records diagnostics without attempting upload.',
    risk: 'safe',
    category: 'publish',
    group: 'publish',
    tags: ['publish', 'auth', 'session-expired', 'edge', 'artifact:html', 'artifact:screenshot'],
    level: 'intermediate',
    implemented: false,
    meta: meta({
      parameters: [{ key: 'fixtureAuthState', value: 'expired cookies / login redirect' }],
      checks: {
        db: ['publish_history failure/precheck status recorded (if row created)', 'Campaign video status reflects auth/session issue without corrupting publish_url'],
        ui: ['User-facing status/error hints re-login is required'],
        logs: ['Exact stage of auth failure logged (open page / redirect / cookie parse)'],
        files: ['Capture screenshot + HTML on login redirect/auth challenge'],
      },
      errorMessages: ['Session expiry should not appear as generic unknown publish exception'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.publish.transient-error-retry-diagnostics',
    title: 'Publish Transient Error Retry Diagnostics',
    description: 'Transient publish/recheck error path captures retry diagnostics, delay values, and artifact bundle for triage.',
    risk: 'safe',
    category: 'publish',
    group: 'publish',
    tags: ['publish', 'retry', 'transient-error', 'diagnostics', 'artifact:html', 'artifact:screenshot'],
    level: 'advanced',
    implemented: false,
    meta: meta({
      parameters: [
        { key: 'fixtureErrorSequence', value: 'timeout -> selector drift -> success/timeout' },
        { key: 'maxAttempts', value: 3 },
      ],
      checks: {
        db: ['Attempt metadata/status progression is persisted (publish_history and/or async task when enabled)'],
        logs: ['Each retry logs reason + next delay + attempt/maxAttempts'],
        files: ['Failure attempts produce HTML/screenshot/session-log artifacts when available'],
      },
      passMessages: ['Retry diagnostics are rich enough to reproduce flaky publish failures'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.publish.debug-artifacts-integrity',
    title: 'Publish Debug Artifact Integrity',
    description: 'When publish runner returns debugArtifacts, stored artifact paths/metadata are valid and visible in troubleshooting run UI.',
    risk: 'safe',
    category: 'publish',
    group: 'publish',
    tags: ['publish', 'artifacts', 'html', 'screenshot', 'session-log', 'ui'],
    level: 'intermediate',
    implemented: false,
    meta: meta({
      parameters: [{ key: 'fixtureResult', value: 'debugArtifacts object with file paths' }],
      checks: {
        db: ['Troubleshooting run record persists sanitized artifact fields in settings'],
        ui: ['Artifacts panel shows html/screenshot/sessionLog entries and copy actions work'],
        logs: ['Artifact save/attach steps logged with file paths'],
        files: ['Referenced artifact paths exist and are readable'],
      },
      passMessages: ['Artifact outputs are preserved and inspectable from debug tab'],
    }),
  }),
]
