import type { TroubleshootingCaseDefinition } from '@main/services/troubleshooting/types'
import { meta, ttCase } from './_shared'

export const recoveryCases: TroubleshootingCaseDefinition[] = [
  ttCase({
    id: 'tiktok-repost-v1.recovery.missed-scheduled-videos',
    title: 'Recovery Reschedules Missed Videos',
    description: 'Crash recovery detects past-due queued videos and reschedules them from now with interval spacing.',
    risk: 'safe',
    category: 'recovery',
    group: 'recovery',
    tags: ['recovery', 'scheduler', 'queued', 'db'],
    level: 'intermediate',
    implemented: true,
    meta: meta({
      parameters: [
        { key: 'fixtureMissedQueuedCount', value: 3 },
        { key: 'intervalMinutes', value: 1 },
      ],
      checks: {
        db: ['Past-due queued videos get new scheduled_for timestamps >= now', 'Rescheduled videos preserve queue order (queue_index)'],
        logs: ['Recovery logs count of rescheduled videos'],
        events: ['Alert panel receives missed-video warning'],
      },
      passMessages: ['Missed schedules are recovered deterministically without dropping videos'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.recovery.reset-under-review',
    title: 'Recovery Resets under_review to queued',
    description: 'Current v1 recovery behavior resets under_review videos to queued and retriggers campaign.',
    risk: 'safe',
    category: 'recovery',
    group: 'recovery',
    tags: ['recovery', 'under_review', 'retry', 'db'],
    level: 'intermediate',
    implemented: true,
    meta: meta({
      parameters: [{ key: 'fixtureUnderReviewCount', value: 2 }],
      checks: {
        db: ['under_review videos become queued after recovery run', 'Campaign save persists status changes'],
        logs: ['Recovery logs reset count under_review→queued', 'Re-trigger only when no pending/running jobs remain'],
      },
      errorMessages: ['Unexpected under_review handling regression is visible in recovery log output'],
      notes: ['This is current v1 behavior and may change once async verify engine takes over.'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.recovery.stuck-running-job-diagnostic',
    title: 'Recovery Stuck Running Job Diagnostic',
    description: 'Detect/diagnose campaign jobs stuck in running state after crash and verify recovery emits actionable logs without corrupting queues.',
    risk: 'safe',
    category: 'recovery',
    group: 'recovery',
    tags: ['recovery', 'jobs', 'running', 'diagnostic', 'db'],
    level: 'advanced',
    implemented: true,
    meta: meta({
      parameters: [{ key: 'fixtureJobState', value: 'running + stale updated_at' }],
      checks: {
        db: ['Stale running job detection does not delete valid queued jobs', 'Campaign/job states remain reloadable after diagnostic path'],
        logs: ['Recovery diagnostic logs include stale job ids/ages and chosen action'],
        events: ['Optional warning alert surfaced for manual intervention'],
      },
      passMessages: ['Recovery produces actionable diagnostics for stuck jobs without destructive side effects'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.recovery.crash-mid-download',
    title: 'Recovery: Crash During Video Download',
    description: 'App crashes while downloading video file (partial file on disk); recovery detects partial file, deletes it, and re-queues video.',
    risk: 'safe',
    category: 'recovery',
    group: 'recovery',
    tags: ['recovery', 'download', 'partial-file', 'crash', 'db'],
    level: 'advanced',
    implemented: true,
    meta: meta({
      parameters: [{ key: 'fixturePartialFileSize', value: '30% of full video' }],
      checks: {
        db: ['Video status reset to queued after partial file detected', 'No stale local_path pointing to partial file'],
        logs: ['Partial file detected and deleted logged', 'Re-queue action recorded with campaign context'],
        events: ['campaign:recovery emitted with reason=partial_download'],
      },
      passMessages: ['Partial download cleaned up; video re-queued for fresh download on next run'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.recovery.db-lock-during-recovery',
    title: 'Recovery: DB Locked During Recovery Write',
    description: 'Another process holds DB write lock during recovery; verify recovery retries gracefully instead of crashing.',
    risk: 'safe',
    category: 'recovery',
    group: 'recovery',
    tags: ['recovery', 'db', 'lock', 'retry', 'edge'],
    level: 'advanced',
    implemented: true,
    meta: meta({
      parameters: [{ key: 'fixtureLockDurationMs', value: 2000 }],
      checks: {
        db: ['Recovery completes after lock is released (with retry)', 'No data corruption from partial recovery write'],
        logs: ['DB lock retry logged with attempt count and wait time'],
        events: ['No campaign corruption event from failed recovery write'],
      },
      passMessages: ['DB lock during recovery is handled with retry; recovery eventually succeeds'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.recovery.corrupted-campaign-doc',
    title: 'Recovery: Corrupted Campaign Document',
    description: 'Campaign data_json is invalid JSON or has null required fields; recovery detects and quarantines the document without crashing other campaigns.',
    risk: 'safe',
    category: 'recovery',
    group: 'recovery',
    tags: ['recovery', 'db', 'corruption', 'edge', 'isolation'],
    level: 'advanced',
    implemented: true,
    meta: meta({
      parameters: [{ key: 'fixtureCorruption', value: 'invalid JSON in data_json field' }],
      checks: {
        db: ['Corrupted campaign is marked with status=corrupt or quarantined, not processed', 'Other healthy campaigns are not affected'],
        logs: ['Parse error logged with campaign_id and corruption type', 'Recovery skips corrupt campaign without crashing boot sequence'],
        events: ['Alert emitted for manual intervention on corrupted campaign'],
      },
      errorMessages: ['Corruption is scoped: only affected campaign is marked, others proceed normally'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.recovery.multi-campaign-parallel-recovery',
    title: 'Recovery: Multiple Campaigns Recover in Parallel',
    description: 'Boot recovery runs on 5 campaigns simultaneously; verify no cross-campaign mutation or deadlock.',
    risk: 'safe',
    category: 'recovery',
    group: 'recovery',
    tags: ['recovery', 'multi-campaign', 'parallel', 'db', 'edge'],
    level: 'advanced',
    implemented: true,
    meta: meta({
      parameters: [{ key: 'fixtureCampaignCount', value: 5 }],
      checks: {
        db: ['Each campaign.videos[] recovered independently without cross-mutation', 'No two campaigns share video rows after recovery'],
        logs: ['Recovery logged per-campaign with campaign_id scope'],
      },
      passMessages: ['Parallel multi-campaign boot recovery is isolated and deadlock-free'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.recovery.idempotent-second-run',
    title: 'Recovery is Idempotent on Repeated Runs',
    description: 'Run boot recovery twice in a row; second run produces no additional state changes.',
    risk: 'safe',
    category: 'recovery',
    group: 'recovery',
    tags: ['recovery', 'idempotent', 'db', 'regression'],
    level: 'intermediate',
    implemented: true,
    meta: meta({
      parameters: [{ key: 'recoveryRunCount', value: 2 }],
      checks: {
        db: ['Campaign state after second recovery === state after first recovery', 'No duplicate reschedule or status flip'],
        logs: ['Second run logs zero changes applied (idempotent outcome)'],
      },
      passMessages: ['Recovery is safe to run multiple times without side effects'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.recovery.failed-counter-drift',
    title: 'Recovery: failed_count Counter Drift After Rescheduling',
    description: 'Recovery resets under_review videos to queued; verify failed_count counter is not double-counted when those videos later fail again.',
    risk: 'safe',
    category: 'recovery',
    group: 'recovery',
    tags: ['recovery', 'counter', 'drift', 'under_review', 'edge'],
    level: 'advanced',
    implemented: true,
    meta: meta({
      parameters: [
        { key: 'fixtureUnderReviewReset', value: 3 },
        { key: 'subsequentFailCount', value: 2 },
      ],
      checks: {
        db: ['campaign.failed_count reflects actual failures, not pre-recovery state', 'No double-count from reset+fail path'],
        logs: ['failed_count update operations logged with delta and context'],
      },
      errorMessages: ['Counter drift detected: expected vs actual failed_count explicit in failure output'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.recovery.boot-job-audit-stale-cleanup',
    title: 'Boot Job Audit: Stale Running Jobs Cleaned Up',
    description: 'On boot, jobs still in running state from crashed session are detected; verify they are reset to failed or re-queued with TTL check.',
    risk: 'safe',
    category: 'recovery',
    group: 'recovery',
    tags: ['recovery', 'jobs', 'boot', 'stale', 'cleanup'],
    level: 'intermediate',
    implemented: true,
    meta: meta({
      parameters: [
        { key: 'fixtureStaleJobAgeMin', value: 60 },
        { key: 'ttlMinutes', value: 30 },
      ],
      checks: {
        db: ['Jobs older than TTL are transitioned to failed or cancelled', 'Jobs within TTL are left for retry'],
        logs: ['Stale job list with age-check results logged on boot'],
        events: ['Alert if stale job count above threshold'],
      },
      passMessages: ['Boot-time stale job cleanup prevents ghost running state accumulation'],
    }),
  }),
]
