import type { TroubleshootingCaseDefinition } from '@main/services/troubleshooting/types'
import { meta, ttCase } from './_shared'

export const scanCases: TroubleshootingCaseDefinition[] = [
  ttCase({
    id: 'tiktok-repost-v1.scan.wizard-sources-main-validation',
    title: 'Wizard Sources Main Validation (Step Contract)',
    description: 'Static analysis of wizard source step to confirm basic validation and filter controls are wired (main path).',
    risk: 'safe',
    category: 'scan',
    group: 'scan',
    tags: ['wizard', 'scan', 'validation', 'static-analysis'],
    level: 'basic',
    implemented: true,
    meta: meta({
      parameters: [
        { key: 'files', value: 'Step2_Sources.tsx + workflows/tiktok-repost/v1.0/wizard.ts' },
      ],
      checks: {
        ui: ['Step2 renders filter controls: Min Likes, Min Views, Max Views, Within Days'],
        logs: ['Runner reports which required controls/validation clauses are present'],
        files: ['Source file paths included in result artifacts for audit'],
      },
      passMessages: ['Main wizard source step contract is present and discoverable'],
      errorMessages: ['Missing core source-step validation or missing filter controls are explicitly listed'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.scan.wizard-sources-edge-validation-gaps',
    title: 'Wizard Sources Edge Validation Gaps',
    description: 'Analyze Step2/wizard edge cases (min/max views, custom range dates, historyLimit coercion) and fail if gaps are found.',
    risk: 'safe',
    category: 'scan',
    group: 'scan',
    tags: ['wizard', 'scan', 'validation', 'edge', 'static-analysis'],
    level: 'advanced',
    implemented: true,
    meta: meta({
      parameters: [{ key: 'focus', value: 'custom_range dates / minViews<=maxViews / numeric coercion' }],
      checks: {
        ui: ['Step2 input constraints exist (HTML min attrs) where applicable'],
        db: ['N/A (code-analysis case)'],
        logs: ['Runner emits gap list with exact file/line clues (text match)'],
        files: ['Source paths returned for AI/debug footprint'],
      },
      errorMessages: ['Case should fail when edge validation gaps still exist (expected during hardening phase)'],
      notes: ['This is intentionally a red test until runtime/wizard validation gaps are fixed.'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.scan.filter-thresholds-fixture',
    title: 'Scanner Filter Thresholds Fixture (min likes/views/max views/withinDays)',
    description: 'Run tiktok-scanner node with mocked TikTokScanner result and assert per-source filtering + thumbnail batch scheduling.',
    risk: 'safe',
    category: 'scan',
    group: 'scan',
    tags: ['scan', 'filters', 'minLikes', 'minViews', 'maxViews', 'withinDays', 'fixture'],
    level: 'basic',
    implemented: true,
    meta: meta({
      parameters: [
        { key: 'source.type', value: 'channel' },
        { key: 'filters', value: 'minLikes=50,minViews=900,maxViews=10000,withinDays=30' },
        { key: 'fixtureVideos', value: 5 },
      ],
      checks: {
        db: ['No DB writes required; node output assertions on filtered list'],
        logs: ['Scanner progress + filter summary logs are captured'],
        events: ['N/A (node context progress only)'],
        files: ['N/A (fixture run)'],
      },
      passMessages: ['Filtered video IDs/count match expected thresholds; thumbnail async batch payload count matches filtered thumbnails'],
      errorMessages: ['Mismatch includes expected vs actual IDs and scheduled thumbnail count'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.scan.channel-smoke',
    title: 'Channel Scan Smoke',
    description: 'Scan source channel and verify videos are added into campaign with expected fields and statuses.',
    risk: 'safe',
    category: 'scan',
    group: 'scan',
    tags: ['scan', 'source', 'db', 'artifact:html', 'artifact:screenshot'],
    level: 'basic',
    implemented: false,
    meta: meta({
      parameters: [
        { key: 'sourceChannel', description: 'Configured source channel/URL fixture' },
        { key: 'maxItems', value: 5, description: 'Suggested smoke cap for deterministic runs' },
      ],
      checks: {
        db: [
          'campaign videos[] appended with source records',
          'Each video has platform_id + data payload + initial status',
          'No malformed thumbnail/caption fields break persistence',
        ],
        ui: ['Campaign detail list reflects scanned items'],
        logs: ['Scanner progress and item count summary logged'],
        files: ['If browser-based scan path is used: dump HTML and screenshot on selector drift/error'],
      },
      errorMessages: ['Empty/failed source response includes request context'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.scan.empty-channel',
    title: 'Channel Scan Empty Result',
    description: 'Source scan returns zero videos and workflow exits/alerts gracefully without crashing.',
    risk: 'safe',
    category: 'scan',
    group: 'scan',
    tags: ['scan', 'empty-result', 'edge'],
    level: 'basic',
    implemented: false,
    meta: meta({
      parameters: [
        { key: 'fixtureResponse', value: 'empty-array' },
      ],
      checks: {
        db: ['No corrupt/placeholder video rows inserted', 'Campaign status/alerts remain consistent'],
        logs: ['Empty result path logged clearly and treated as handled outcome'],
        events: ['Optional warning/info alert emitted to user'],
      },
      passMessages: ['Workflow handles zero-result scan without exception'],
      errorMessages: ['Unexpected null/undefined payload path is visible in logs'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.scan.session-expired',
    title: 'Channel Scan Session Expired',
    description: 'Simulate expired session/cookies during scan and verify error handling / user-facing logs.',
    risk: 'safe',
    category: 'scan',
    group: 'scan',
    tags: ['scan', 'auth', 'session-expired', 'edge', 'artifact:html', 'artifact:screenshot'],
    level: 'intermediate',
    implemented: false,
    meta: meta({
      parameters: [
        { key: 'fixtureAuthState', value: 'expired-session' },
      ],
      checks: {
        db: ['No partial/corrupt video rows persisted on auth failure'],
        ui: ['User-facing error/alert indicates session expired / re-login required'],
        logs: ['Auth failure path includes exact stage and redirect URL if browser-based'],
        files: ['Capture screenshot and HTML on login redirect/auth challenge'],
      },
      errorMessages: ['Session expired is distinguished from network/selector failures'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.scan.selector-drift-dump-artifacts',
    title: 'Channel Scan Selector Drift Diagnostics',
    description: 'Force/fixture selector mismatch in browser scan path and verify HTML + screenshot dumps are preserved for debugging.',
    risk: 'safe',
    category: 'scan',
    group: 'scan',
    tags: ['scan', 'selector-drift', 'edge', 'artifact:html', 'artifact:screenshot'],
    level: 'advanced',
    implemented: false,
    meta: meta({
      parameters: [
        { key: 'fixtureMode', value: 'selector-mismatch' },
        { key: 'dumpArtifactsOnFail', value: true },
      ],
      checks: {
        db: ['No partially parsed/corrupt scan entries are persisted'],
        logs: ['Selector miss includes selector names/stage URL in logs'],
        files: ['HTML dump exists', 'Screenshot exists', 'Artifact paths included in run result'],
      },
      passMessages: ['Artifact bundle is sufficient for offline selector debugging'],
      errorMessages: ['Generic "scan failed" without artifact path is considered insufficient'],
    }),
  }),
  ttCase({
    id: 'tiktok-repost-v1.scan.rescan-dedupe-existing-items',
    title: 'Channel Re-scan Dedupe Existing Items',
    description: 'Re-scan same source and verify existing videos are deduped/merged rather than duplicated in campaign.',
    risk: 'safe',
    category: 'scan',
    group: 'scan',
    tags: ['scan', 'dedupe', 'db', 'edge'],
    level: 'intermediate',
    implemented: false,
    meta: meta({
      parameters: [
        { key: 'fixtureInitialVideos', value: 5 },
        { key: 'fixtureRescanOverlap', value: '3 existing + 2 new' },
      ],
      checks: {
        db: ['Existing videos matched by platform_id are not duplicated', 'New items append correctly with stable ordering'],
        logs: ['Dedup/merge counts are logged (existing/new/skipped)'],
      },
      passMessages: ['Rescan is idempotent for already-imported source items'],
    }),
  }),
]
