const FIXTURE_NOW = Date.now()

const PNG_DATA_URL =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAgMBgA4Mqb0AAAAASUVORK5CYII='

export const TROUBLESHOOTING_PANEL_FIXTURE_CASES = [
  {
    id: 'fixture.case.e2e.publish-path',
    title: 'Fixture E2E Publish Path',
    description: 'Simulates real publish failure with rich artifacts for UI diagnostics.',
    risk: 'real_publish',
    workflowId: 'tiktok-repost',
    workflowVersion: '1.0',
    category: 'publish',
    group: 'publish',
    tags: ['e2e', 'publish', 'artifact:screenshot', 'artifact:html'],
    level: 'advanced',
    implemented: true,
  },
  {
    id: 'fixture.case.integration.db-merge',
    title: 'Fixture Integration DB Merge',
    description: 'Integration fixture for DB merge/result payload preview.',
    risk: 'safe',
    workflowId: 'tiktok-repost',
    workflowVersion: '1.0',
    category: 'scan',
    group: 'scan',
    tags: ['db', 'integration', 'scan'],
    level: 'intermediate',
    implemented: true,
  },
  {
    id: 'fixture.case.integration.events-stream',
    title: 'Fixture Integration Events Stream',
    description: 'Integration fixture for event/log heavy path.',
    risk: 'safe',
    workflowId: 'tiktok-repost',
    workflowVersion: '1.0',
    category: 'campaign',
    group: 'campaign',
    tags: ['events', 'integration', 'campaign'],
    level: 'intermediate',
    implemented: true,
  },
  {
    id: 'fixture.case.unit.static-analysis',
    title: 'Fixture Unit Static Analysis',
    description: 'Unit fixture used for suite grouping checks.',
    risk: 'safe',
    workflowId: 'tiktok-repost',
    workflowVersion: '1.0',
    category: 'scan',
    group: 'scan',
    tags: ['static-analysis', 'unit'],
    level: 'basic',
    implemented: true,
  },
  {
    id: 'fixture.case.unit.contract-guard',
    title: 'Fixture Unit Contract Guard',
    description: 'Unit fixture with contract tag.',
    risk: 'safe',
    workflowId: 'main',
    workflowVersion: '1.0',
    category: 'unit',
    group: 'external-unit',
    tags: ['contract', 'unit'],
    level: 'basic',
    implemented: true,
  },
  {
    id: 'fixture.case.main.catalog-smoke',
    title: 'Fixture Main Catalog Smoke',
    description: 'Main workflow smoke fixture.',
    risk: 'safe',
    workflowId: 'main',
    workflowVersion: '1.0',
    category: 'smoke',
    group: 'smoke',
    tags: ['catalog-only'],
    level: 'basic',
    implemented: true,
  },
  {
    id: 'fixture.case.tiktok.v2.edge',
    title: 'Fixture TikTok v2 Edge',
    description: 'Workflow version v2 edge fixture.',
    risk: 'safe',
    workflowId: 'tiktok-repost',
    workflowVersion: '2.0',
    category: 'scan',
    group: 'scan',
    tags: ['db', 'edge'],
    level: 'advanced',
    implemented: true,
  },
  {
    id: 'fixture.case.tiktok.v2.browser-e2e',
    title: 'Fixture TikTok v2 Browser E2E',
    description: 'Browser-tagged v2 fixture to ensure e2e suite classification.',
    risk: 'safe',
    workflowId: 'tiktok-repost',
    workflowVersion: '2.0',
    category: 'publish',
    group: 'publish',
    tags: ['browser', 'artifact:screenshot'],
    level: 'advanced',
    implemented: true,
  },
  {
    id: 'fixture.case.upload.planned-only',
    title: 'Fixture Upload Planned Only',
    description: 'Planned-only workflow fixture (non-runnable).',
    risk: 'safe',
    workflowId: 'upload-local',
    workflowVersion: '1.0',
    category: 'smoke',
    group: 'smoke',
    tags: ['upload-local'],
    level: 'basic',
    implemented: false,
  },
]

export const TROUBLESHOOTING_PANEL_FIXTURE_WORKFLOWS = [
  {
    workflowId: 'main',
    workflowVersion: '1.0',
    totalCases: 2,
    runnableCases: 2,
    plannedCases: 0,
  },
  {
    workflowId: 'tiktok-repost',
    workflowVersion: '1.0',
    totalCases: 4,
    runnableCases: 4,
    plannedCases: 0,
  },
  {
    workflowId: 'tiktok-repost',
    workflowVersion: '2.0',
    totalCases: 2,
    runnableCases: 2,
    plannedCases: 0,
  },
  {
    workflowId: 'upload-local',
    workflowVersion: '1.0',
    totalCases: 1,
    runnableCases: 0,
    plannedCases: 1,
  },
]

export const TROUBLESHOOTING_PANEL_FIXTURE_ACCOUNTS = [
  { id: 'acc-fixture-1', username: 'fixture_alpha', handle: '@fixture_alpha', status: 'active' },
  { id: 'acc-fixture-2', username: 'fixture_beta', handle: '@fixture_beta', status: 'paused' },
]

export const TROUBLESHOOTING_PANEL_FIXTURE_VIDEO_CANDIDATES = [
  {
    id: 'video-fixture-1',
    workflowId: 'tiktok-repost',
    workflowVersion: '1.0',
    campaignId: 'camp_tiktok_v1',
    campaignName: 'TikTok V1 Campaign',
    platformId: 'vid_v1_001',
    status: 'queued',
    localPath: 'C:\\videos\\fixture-v1-001.mp4',
  },
  {
    id: 'video-fixture-2',
    workflowId: 'tiktok-repost',
    workflowVersion: '2.0',
    campaignId: 'camp_tiktok_v2',
    campaignName: 'TikTok V2 Campaign',
    platformId: 'vid_v2_001',
    status: 'downloaded',
    localPath: '/tmp/videos/fixture-v2-001.mp4',
  },
  {
    id: 'video-fixture-3',
    workflowId: 'upload-local',
    workflowVersion: '1.0',
    campaignId: 'camp_upload_v1',
    campaignName: 'Upload Local Campaign',
    platformId: 'vid_upload_001',
    status: 'queued',
    localPath: 'C:\\uploads\\fixture-upload-001.mp4',
  },
]

export const TROUBLESHOOTING_PANEL_FIXTURE_SOURCE_CANDIDATES = [
  {
    id: 'source-fixture-1',
    workflowId: 'tiktok-repost',
    workflowVersion: '1.0',
    campaignId: 'camp_tiktok_v1',
    campaignName: 'TikTok V1 Campaign',
    sourceType: 'channel',
    sourceName: '@fixture_channel',
    minViews: 1000,
    minLikes: 50,
  },
  {
    id: 'source-fixture-2',
    workflowId: 'tiktok-repost',
    workflowVersion: '2.0',
    campaignId: 'camp_tiktok_v2',
    campaignName: 'TikTok V2 Campaign',
    sourceType: 'keyword',
    sourceName: '#fixturetag',
    minViews: 500,
    minLikes: 20,
  },
  {
    id: 'source-fixture-3',
    workflowId: 'upload-local',
    workflowVersion: '1.0',
    campaignId: 'camp_upload_v1',
    campaignName: 'Upload Local Campaign',
    sourceType: 'folder',
    sourceName: 'C:\\uploads\\inbox',
  },
]

export const TROUBLESHOOTING_PANEL_FIXTURE_RUNS = [
  {
    id: 'fixture-run-failed-v1',
    caseId: 'fixture.case.e2e.publish-path',
    title: 'Fixture Publish Failed Run',
    status: 'failed',
    startedAt: FIXTURE_NOW - 30000,
    endedAt: FIXTURE_NOW - 28000,
    summary: 'Fixture publish failed with selector drift diagnostics.',
    workflowId: 'tiktok-repost',
    workflowVersion: '1.0',
    category: 'publish',
    group: 'publish',
    tags: ['e2e', 'artifact:screenshot', 'artifact:html'],
    level: 'advanced',
    caseFingerprint: 'case-fixture-e2e-v1',
    runFingerprint: 'run-fixture-e2e-v1',
    artifactManifestPath: 'C:/tmp/debug-artifacts/fixture-run-failed-v1/artifact-manifest.json',
    footprintPath: 'C:/tmp/debug-footprints/fixture-run-failed-v1.json',
    logs: [
      { ts: FIXTURE_NOW - 29500, level: 'warn', line: 'Upload selector fallback #1 failed.' },
      { ts: FIXTURE_NOW - 29200, level: 'error', line: 'Could not find submit button after retries.' },
    ],
    logStats: { total: 12, info: 8, warn: 2, error: 2 },
    caseMeta: {
      parameters: [
        { key: 'expectedOutcome', value: 'selector-drift' },
        { key: 'workflowVersion', value: '1.0' },
      ],
      checks: {
        db: ['No publish_history row for failed selector drift upload'],
        ui: ['Failure status visible in run history'],
        logs: ['Selector retries and final error are logged'],
      },
      artifacts: [
        { key: 'screenshot', type: 'screenshot' },
        { key: 'screenshotPath', type: 'screenshot' },
        { key: 'html', type: 'html' },
        { key: 'sessionLog', type: 'session-log' },
      ],
      passMessages: ['Diagnostics are rich enough for offline triage'],
      errorMessages: ['Selector drift should show explicit failure stage'],
      notes: ['Fixture run for artifact and footprint rendering checks.'],
    },
    result: {
      artifacts: {
        screenshot: PNG_DATA_URL,
        screenshotPath: 'C:\\debug\\fixtures\\selector-drift.png',
        html: '<html><body><h1>Selector drift fixture</h1></body></html>',
        sessionLog: 'step=upload_opened\nstep=selector_retry\nstep=failed',
      },
      debugArtifacts: {
        screenshot: PNG_DATA_URL,
      },
    },
    diagnosticFootprint: {
      schemaVersion: 1,
      execution: { durationMs: 1840 },
      signals: { errorCount: 1, warnCount: 2 },
      checks: { failed: ['selector_submit_button_found'] },
    },
  },
  {
    id: 'fixture-run-passed-integration',
    caseId: 'fixture.case.integration.db-merge',
    title: 'Fixture Integration Passed Run',
    status: 'passed',
    startedAt: FIXTURE_NOW - 24000,
    endedAt: FIXTURE_NOW - 22000,
    summary: 'Fixture DB merge integration passed.',
    workflowId: 'tiktok-repost',
    workflowVersion: '1.0',
    category: 'scan',
    group: 'scan',
    tags: ['integration', 'db'],
    level: 'intermediate',
    logs: [{ ts: FIXTURE_NOW - 23200, level: 'info', line: 'Merged 3 rows, deduped 1 row.' }],
    logStats: { total: 1, info: 1, warn: 0, error: 0 },
    caseMeta: {
      artifacts: [
        { key: 'debugSummary', type: 'text' },
        { key: 'payloadJson', type: 'json' },
      ],
    },
    result: {
      artifacts: {
        debugSummary: 'DB merge completed successfully.',
        payloadJson: '{"inserted":2,"deduped":1,"updated":1}',
      },
    },
  },
  {
    id: 'fixture-run-running-unit',
    caseId: 'fixture.case.unit.static-analysis',
    title: 'Fixture Unit Running Run',
    status: 'running',
    startedAt: FIXTURE_NOW - 18000,
    summary: 'Static analysis run in progress.',
    workflowId: 'tiktok-repost',
    workflowVersion: '1.0',
    category: 'scan',
    group: 'scan',
    tags: ['unit'],
    level: 'basic',
    logs: [{ ts: FIXTURE_NOW - 17000, level: 'info', line: 'Scanning static guards...' }],
    logStats: { total: 1, info: 1, warn: 0, error: 0 },
    result: {},
  },
  {
    id: 'fixture-run-main-no-artifacts',
    caseId: 'fixture.case.main.catalog-smoke',
    title: 'Fixture Main Passed Run',
    status: 'passed',
    startedAt: FIXTURE_NOW - 12000,
    endedAt: FIXTURE_NOW - 11000,
    summary: 'Main catalog smoke passed (no artifacts/footprint).',
    workflowId: 'main',
    workflowVersion: '1.0',
    category: 'smoke',
    group: 'smoke',
    tags: ['catalog-only'],
    level: 'basic',
    logs: [{ ts: FIXTURE_NOW - 11500, level: 'info', line: 'Catalog loaded.' }],
    logStats: { total: 1, info: 1, warn: 0, error: 0 },
    result: {},
  },
  {
    id: 'fixture-run-v2-failed',
    caseId: 'fixture.case.tiktok.v2.edge',
    title: 'Fixture V2 Failed Run',
    status: 'failed',
    startedAt: FIXTURE_NOW - 9000,
    endedAt: FIXTURE_NOW - 8000,
    summary: 'v2 edge fixture failed with timeout.',
    workflowId: 'tiktok-repost',
    workflowVersion: '2.0',
    category: 'scan',
    group: 'scan',
    tags: ['edge'],
    level: 'advanced',
    logs: [{ ts: FIXTURE_NOW - 8500, level: 'error', line: 'Timeout at pagination page=4.' }],
    logStats: { total: 1, info: 0, warn: 0, error: 1 },
    result: {
      artifacts: {
        timeoutDetails: 'page=4 timeout after 10s',
      },
    },
  },
  {
    id: 'fixture-run-v2-no-logs',
    caseId: 'fixture.case.tiktok.v2.browser-e2e',
    title: 'Fixture V2 Passed No Logs',
    status: 'passed',
    startedAt: FIXTURE_NOW - 7600,
    endedAt: FIXTURE_NOW - 7400,
    summary: 'v2 browser path passed without emitted logs.',
    workflowId: 'tiktok-repost',
    workflowVersion: '2.0',
    category: 'publish',
    group: 'publish',
    tags: ['browser', 'artifact:screenshot'],
    level: 'advanced',
    logs: [],
    logStats: { total: 0, info: 0, warn: 0, error: 0 },
    result: {
      artifacts: {
        screenshot: PNG_DATA_URL,
      },
    },
  },
  {
    id: 'fixture-run-ghost-hidden',
    caseId: 'fixture.case.ghost.hidden',
    title: 'Fixture Ghost Hidden Run',
    status: 'failed',
    startedAt: FIXTURE_NOW - 7000,
    endedAt: FIXTURE_NOW - 6000,
    summary: 'Run belongs to removed workflow and should be hidden.',
    workflowId: 'ghost-workflow',
    workflowVersion: '9.9',
    category: 'ghost',
    group: 'ghost',
    tags: ['ghost'],
    level: 'advanced',
    logs: [{ ts: FIXTURE_NOW - 6500, level: 'error', line: 'Ghost workflow run should not be listed.' }],
    logStats: { total: 1, info: 0, warn: 0, error: 1 },
    result: {},
  },
]
