export const TROUBLESHOOTING_PANEL_FIXTURE_CASES = [
  {
    id: 'fixture.case.e2e',
    title: 'Fixture E2E',
    description: 'E2E suite fixture',
    risk: 'real_publish',
    workflowId: 'tiktok-repost',
    workflowVersion: '1.0',
    category: 'publish',
    group: 'publish',
    tags: ['e2e', 'publish'],
    level: 'advanced',
    implemented: true,
  },
  {
    id: 'fixture.case.integration',
    title: 'Fixture Integration',
    description: 'Integration suite fixture',
    risk: 'safe',
    workflowId: 'tiktok-repost',
    workflowVersion: '1.0',
    category: 'scan',
    group: 'scan',
    tags: ['db'],
    level: 'intermediate',
    implemented: true,
  },
  {
    id: 'fixture.case.unit',
    title: 'Fixture Unit',
    description: 'Unit suite fixture',
    risk: 'safe',
    workflowId: 'tiktok-repost',
    workflowVersion: '1.0',
    category: 'scan',
    group: 'scan',
    tags: ['static-analysis'],
    level: 'basic',
    implemented: true,
  },
]

export const TROUBLESHOOTING_PANEL_FIXTURE_RUNS = [
  {
    id: 'fixture-run-1',
    caseId: 'fixture.case.e2e',
    title: 'Fixture Run',
    status: 'failed',
    startedAt: Date.now() - 10000,
    endedAt: Date.now() - 5000,
    summary: 'Fixture artifact run',
    workflowId: 'tiktok-repost',
    workflowVersion: '1.0',
    category: 'publish',
    group: 'publish',
    tags: ['e2e', 'artifact:screenshot'],
    level: 'advanced',
    logs: [{ ts: Date.now() - 9000, level: 'error', line: 'fixture error' }],
    logStats: { total: 1, info: 0, warn: 0, error: 1 },
    caseMeta: {
      artifacts: [{ key: 'screenshot', type: 'screenshot' }],
    },
    result: {
      artifacts: {
        screenshot: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAgMBgA4Mqb0AAAAASUVORK5CYII=',
      },
    },
  },
]
