import {
  clearLogsCase,
  plannedCaseButtonDisabledCase,
  refreshMaintainsRunHistoryCase,
  runAllAddsMultipleRunsCase,
  runAllEnabledWhenRunnableCase,
  runAllDisabledPlannedOnlyCase,
  runCaseAddsHistoryEntryCase,
} from './actions.case.mjs'
import { groupingSuitesCase } from './grouping-suites.case.mjs'
import {
  manualPickersCandidateLoadCase,
  manualPickersCandidateResetCase,
  manualPickersDisabledCase,
  manualPickersSummaryCase,
  manualSeedSummaryWithoutManualPickersCase,
  manualPickersWarningCase,
} from './manual-pickers.case.mjs'
import {
  artifactEmptyStateCase,
  artifactImagePathPreviewCase,
  artifactTextPreviewCase,
  cappedLogHintCase,
  failedRunSentryActionCase,
  footprintStatsCase,
  footprintEmptyStateCase,
  fullLogModalCase,
  fullLogModalSnapshotContextCase,
  noLogsStateCase,
  passedRunNoSentryActionCase,
  runCaseMetaEmptyStateCase,
  runCaseMetaSectionsCase,
  runSummaryFingerprintPathCase,
} from './run-details.case.mjs'
import { sentryFeedbackLinksCase } from './sentry-feedback-links.case.mjs'
import { screenshotPreviewCase } from './screenshot-preview.case.mjs'
import {
  hiddenWorkflowRunPrunedCase,
  workflowCardFilterCase,
  workflowCatalogCase,
  workflowSelectOptionsCase,
  workflowVersionFilterCase,
  workflowVersionOptionCase,
  workflowVersionResetsOnScopeChangeCase,
} from './workflow-catalog.case.mjs'

/** @type {import('../types.mjs').E2ECaseGroup} */
export const troubleshootingPanelCaseGroup = {
  id: 'troubleshooting-panel',
  label: 'Troubleshooting Panel',
  meta: {
    objective: 'Validate troubleshooting catalog grouping and artifact preview UX.',
    investigationHints: [
      'Use case id to run a single failing flow with TEST_CASE_ID.',
      'Inspect fixture payload in tests/e2e/cases/troubleshooting/fixtures.mjs.',
    ],
  },
  cases: [
    groupingSuitesCase,
    workflowCatalogCase,
    workflowSelectOptionsCase,
    workflowVersionOptionCase,
    workflowVersionFilterCase,
    workflowVersionResetsOnScopeChangeCase,
    workflowCardFilterCase,
    hiddenWorkflowRunPrunedCase,
    manualPickersWarningCase,
    manualPickersDisabledCase,
    manualPickersCandidateLoadCase,
    manualPickersCandidateResetCase,
    manualPickersSummaryCase,
    manualSeedSummaryWithoutManualPickersCase,
    failedRunSentryActionCase,
    passedRunNoSentryActionCase,
    runSummaryFingerprintPathCase,
    runCaseMetaSectionsCase,
    runCaseMetaEmptyStateCase,
    artifactTextPreviewCase,
    artifactImagePathPreviewCase,
    artifactEmptyStateCase,
    cappedLogHintCase,
    footprintEmptyStateCase,
    footprintStatsCase,
    fullLogModalCase,
    fullLogModalSnapshotContextCase,
    noLogsStateCase,
    screenshotPreviewCase,
    runCaseAddsHistoryEntryCase,
    runAllAddsMultipleRunsCase,
    runAllEnabledWhenRunnableCase,
    runAllDisabledPlannedOnlyCase,
    plannedCaseButtonDisabledCase,
    refreshMaintainsRunHistoryCase,
    sentryFeedbackLinksCase,
    clearLogsCase,
  ],
}
