import {
  autoRandomSeedSummaryVisibleCase,
  clearLogsResetsRunPanelsCase,
  filterSummaryReflectsSelectionsCase,
  fullLogModalOpenCloseCase,
  fullLogModalSnapshotContextCase,
  manualPickersScopedDisabledWhenToggleOffCase,
  manualPickersScopedEnabledCase,
  manualPickersWarningCase,
  panelLoadsRealCatalogCase,
  plannedCaseButtonDisabledCase,
  refreshKeepsPanelInteractiveCase,
  runCaseAddsHistoryEntryCase,
  runAllDisabledForPlannedOnlyWorkflowCase,
  runAllEnabledForRunnableWorkflowCase,
  runDetailsFootprintStatsCase,
  runDetailsLogStatsVisibleCase,
  runDetailsResultPayloadCase,
  runDetailsSectionsVisibleAfterRunCase,
  runDetailsSummaryFingerprintsAndPathsCase,
  runHistoryAndDetailsEmptyStateCase,
  runHistoryScopedByWorkflowCase,
  runHistoryStatusChipPassedCase,
  sentryActionHiddenForPassedRunCase,
  versionSelectOptionsCase,
  workflowCatalogCase,
  workflowCardFilterCase,
  workflowCardSelectionSyncsFilterInputsCase,
  workflowSelectOptionsCase,
} from './real-ui.case.mjs'

/** @type {import('../types.mjs').E2ECaseGroup} */
export const troubleshootingPanelCaseGroup = {
  id: 'troubleshooting-panel',
  label: 'Troubleshooting Panel',
  meta: {
    objective: 'Validate troubleshooting panel against real Electron UI + IPC without mocked window.api.',
    investigationHints: [
      'Use case id to run a single failing flow with TEST_CASE_ID.',
      'Tests must run against real app state, not fixture-mocked API payloads.',
    ],
  },
  cases: [
    panelLoadsRealCatalogCase,
    workflowCatalogCase,
    workflowSelectOptionsCase,
    workflowCardSelectionSyncsFilterInputsCase,
    versionSelectOptionsCase,
    filterSummaryReflectsSelectionsCase,
    workflowCardFilterCase,
    runHistoryAndDetailsEmptyStateCase,
    runAllDisabledForPlannedOnlyWorkflowCase,
    runAllEnabledForRunnableWorkflowCase,
    manualPickersWarningCase,
    manualPickersScopedEnabledCase,
    manualPickersScopedDisabledWhenToggleOffCase,
    autoRandomSeedSummaryVisibleCase,
    refreshKeepsPanelInteractiveCase,
    plannedCaseButtonDisabledCase,
    runHistoryScopedByWorkflowCase,
    runCaseAddsHistoryEntryCase,
    runHistoryStatusChipPassedCase,
    runDetailsSectionsVisibleAfterRunCase,
    runDetailsSummaryFingerprintsAndPathsCase,
    runDetailsFootprintStatsCase,
    runDetailsLogStatsVisibleCase,
    runDetailsResultPayloadCase,
    fullLogModalOpenCloseCase,
    fullLogModalSnapshotContextCase,
    sentryActionHiddenForPassedRunCase,
    clearLogsResetsRunPanelsCase,
  ],
}
