import { nodeRegistry } from '../nodes/NodeRegistry'
import { jobRepo } from '@main/db/repositories/JobRepo'
import { campaignRepo, CampaignStore } from '@main/db/repositories/CampaignRepo'
import { FlowResolver } from '../flow/FlowResolver'
import { flowLoader } from '../flow/FlowLoader'
import { ExecutionLogger } from './ExecutionLogger'
import { FlowDefinition, FlowNodeDefinition } from '../flow/ExecutionContracts'
import type { JobDocument } from '@main/db/models/Job'
import { asyncTaskScheduler } from '@main/services/AsyncTaskScheduler'
import { isNetworkError, isDiskError } from '../nodes/NodeHelpers'
import { getFreeDiskSpaceMB } from '@main/utils/diskSpace'

